### ISSUE TITLE
PhpDotNet Roadmap for Release 1.0.0

### ISSUE THREAD

**Issue by JustinianErdmier** [JustinErdmier/PhpDotNet#1]
# Roadmap
This issue represents the list of goals and objectives being prioritized for developing and releasing the production-ready release v1.0.0 of PhpDotNet. It does not include all the features and bugfixes which will be tackled.

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go but will try to keep this issue up to date to reflect on our progress and learning.

The roadmap consists of two major areas below.

## Routing

- [ ] Fully implement route configuration via attributes.
- [ ] Design and implement route templating.
  - [ ]  Implement REGEX based route resolution for improved performance.
- [ ] Implement route parameters and model binding.

## View Templating

- [ ] Fully implement a strongly typed view templating engine. Possibly Twig.
- [ ] Fully implement strongly type view creation/returns from controller action methods.
- [ ] Design and implement view discovery patterns.
  - [ ] Ties into route templating.
